idempotent create post
asteny/urlcut pull request #5
Opened 2021-03-02 20:33 UTC by asteny

2021-03-03 06:41 UTC, Pavkazzz commented on urlcut/handlers/urls.py
>          short_url_path = await insert_url_data(
В принципе можешь сделать uniq индекс на поля которые будут меняться и ловить indexconflict. Чтобы не читать отдельно из базы

2021-03-03 06:43 UTC, Pavkazzz requested changes

2021-03-03 06:43 UTC, Pavkazzz commented on urlcut/models/db_query.py
> +async def get_link_state(db: pool, short_path: str) -> Record:
А не links_table тут вернется?

2021-03-03 06:43 UTC, Pavkazzz commented on urlcut/handlers/urls.py
>          short_url_path = await insert_url_data(
И транзакцию забыл, если отдельно читать будешь

2021-03-04 06:14 UTC, asteny commented on urlcut/models/db_query.py
> +async def get_link_state(db: pool, short_path: str) -> Record:
Все верно:

`<class 'asyncpg.Record'>`

2021-03-07 08:00 UTC, Pavkazzz approved these changes

2021-03-07 08:03 UTC, merged