put method for update link
asteny/urlcut pull request #8
Opened 2021-03-11 17:28 UTC by asteny

2021-03-11 17:44 UTC, Pavkazzz requested changes

2021-03-11 17:44 UTC, Pavkazzz commented on urlcut/handlers/urls.py
> +            return json_response(status=HTTPStatus.CREATED)
Говорят нужно все отдать, как и при GET запросе

2021-03-11 17:44 UTC, Pavkazzz commented on urlcut/models/db_query.py
> +        id_query = (
А зачем тебе select? Просто делай update и смотри что вернула базка

2021-03-12 07:14 UTC, asteny commented on urlcut/handlers/urls.py
> +            return json_response(status=HTTPStatus.CREATED)
не... https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/PUT

2021-03-12 07:21 UTC, Pavkazzz approved these changes

2021-03-12 07:22 UTC, merged